"""Write out the schema the database actually has.

Read-only. Generated rather than hand-written, because a hand-written schema
document is wrong the first time anyone adds a property and nothing ever says
so. Anything that needs to describe the graph - an agent prompt, a dashboard
query, a person trying to remember what `pfo_sec_q_inf` is - should start here.

    uv run python -m graph_node.schema            # to stdout
    uv run python -m graph_node.schema -o SCHEMA.md

What it reports, per label: the identity property that MERGE matches on, which
loader owns it, how many nodes exist, and every property with its stored type.
Types come from the database, not from the loader's intentions, which is how
`step_index: FLOAT` was caught after the first live rebuild.
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from datetime import datetime, timezone

from neo4j import GraphDatabase

from .common import ids
from .common.config import Settings
from .common.ownership import ALL_SCOPES
from .common.rebuild import RUN_PROPERTY
from .common.tls import use_system_trust_store


def _scope_of(label: str) -> str:
    for scope in ALL_SCOPES:
        if scope.owns_label(label):
            return scope.name
    return "unowned"


def collect(session) -> dict:
    counts = {
        r["label"]: r["count"]
        for r in session.run(
            "MATCH (n) UNWIND labels(n) AS label "
            "RETURN label, count(*) AS count ORDER BY label"
        )
    }
    patterns = [
        (r["start"], r["type"], r["end"], r["count"])
        for r in session.run(
            "MATCH (a)-[r]->(b) "
            "RETURN labels(a)[0] AS start, type(r) AS type, labels(b)[0] AS end, "
            "count(*) AS count ORDER BY type, start, end"
        )
    ]
    properties: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for r in session.run("CALL db.schema.nodeTypeProperties()"):
        labels = r["nodeLabels"] or []
        if not labels:
            continue
        types = ", ".join(r["propertyTypes"] or []) or "unknown"
        properties[labels[0]].append((r["propertyName"], types))
    return {"counts": counts, "patterns": patterns, "properties": properties}


def render(data: dict, uri: str) -> str:
    counts, patterns, properties = data["counts"], data["patterns"], data["properties"]
    host = uri.split("://")[-1].split(".")[0]
    out = [
        "# Graph schema",
        "",
        "Generated by `uv run python -m graph_node.schema`. Do not edit by hand -",
        "it is read out of the live database, so anything typed here is lost on the",
        "next run and wrong in the meantime.",
        "",
        f"- instance: `{host}...` ",
        f"- generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        f"- nodes: {sum(counts.values()):,}",
        "",
        "## Labels",
        "",
        "| Label | Nodes | Identity property | Owned by |",
        "|---|---:|---|---|",
    ]
    for label in sorted(set(counts) | set(ids.IDENTITY)):
        prop = ids.IDENTITY.get(label, (None, None))[0] or "-"
        out.append(
            f"| `{label}` | {counts.get(label, 0):,} | `{prop}` | {_scope_of(label)} |"
        )

    out += ["", "## Relationships", "", "| Pattern | Count |", "|---|---:|"]
    for start, rel, end, count in patterns:
        out.append(f"| `(:{start})-[:{rel}]->(:{end})` | {count:,} |")

    out += ["", "## Properties", ""]
    for label in sorted(properties):
        identity = ids.IDENTITY.get(label, (None, None))[0]
        out += [f"### {label}  ({counts.get(label, 0):,} nodes)", ""]
        out += ["| Property | Type | |", "|---|---|---|"]
        for name, types in sorted(properties[label]):
            note = ""
            if name == identity:
                note = "identity - MERGE matches on this"
            elif name == RUN_PROPERTY:
                note = "rebuild stamp; anything unstamped is swept"
            out.append(f"| `{name}` | {types} | {note} |")
        out.append("")

    declared_empty = [
        label
        for label in sorted(ids.IDENTITY)
        if counts.get(label, 0) == 0
    ]
    if declared_empty:
        out += [
            "## Declared but empty",
            "",
            "Labels the loaders know about that have no nodes yet - a schema"
            " addition that has not been written.",
            "",
        ]
        out += [f"- `{label}` ({_scope_of(label)})" for label in declared_empty]
        out.append("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="graph-node-schema", description="Print the live graph schema."
    )
    parser.add_argument("-o", "--output", help="Write here instead of stdout.")
    args = parser.parse_args(argv)

    use_system_trust_store()
    settings = Settings.from_env(None)
    driver = GraphDatabase.driver(
        settings.uri, auth=(settings.username, settings.password)
    )
    try:
        with driver.session(database=settings.database) as session:
            text = render(collect(session), settings.uri)
    finally:
        driver.close()

    if args.output:
        with open(args.output, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text + "\n")
        print(f"wrote {args.output}", file=sys.stderr)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
